#配置端口
server:
  port: 8098
  servlet-path: /imis

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/imis
    username: root
    password: 123456
  profiles:
    active: dev
